version: "3.8"

services:
  blue:
    image: ${BLUE_IMAGE}
    container_name: blue
    ports:
      - "${BLUE_PORT}:3000"
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3

  green:
    image: ${GREEN_IMAGE}
    container_name: green
    ports:
      - "${GREEN_PORT}:3000"
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    image: ${NGINX_IMAGE}
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - blue
      - green
    volumes:
      - ./nginx/template/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/entrypoint.sh:/docker-entrypoint.d/entrypoint.sh:ro
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
